package com.hb.system.ecommerce.shoes.DataIniatilizer;

import java.util.List;

import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;

import com.hb.system.ecommerce.shoes.entity.Department;
import com.hb.system.ecommerce.shoes.entity.Province;
import com.hb.system.ecommerce.shoes.repositories.DepartmentRepository;
import com.hb.system.ecommerce.shoes.repositories.ProvinceRepository;
import org.springframework.transaction.annotation.Transactional;


@Configuration
@RequiredArgsConstructor
public class ProvinceInitializer {
    private final ProvinceRepository provinceRepository;
    private final DepartmentRepository departmentRepository;

    @Bean
    @Transactional
    @Order(5)
    public CommandLineRunner initProvinces() {
        return args -> {
            if (provinceRepository.count() == 0) {
                List<Province> provinces = List.of(
                        new Province("Chachapoyas", getDepartment(1)),
                        new Province("Bagua", getDepartment(1)),
                        new Province("Bongara", getDepartment(1)),
                        new Province("Condorcanqui", getDepartment(1)),
                        new Province("Luya", getDepartment(1)),
                        new Province("Rodriguez de Mendoza", getDepartment(1)),
                        new Province("Utcubamba", getDepartment(1)),
                        new Province("Huaraz", getDepartment(2)),
                        new Province("Aija", getDepartment(2)),
                        new Province("Antonio Raymondi", getDepartment(2)),
                        new Province("Asuncion", getDepartment(2)),
                        new Province("Bolognesi", getDepartment(2)),
                        new Province("Carhuaz", getDepartment(2)),
                        new Province("Carlos Fermin Fitzcarrald", getDepartment(2)),
                        new Province("Casma", getDepartment(2)),
                        new Province("Corongo", getDepartment(2)),
                        new Province("Huari", getDepartment(2)),
                        new Province("Huarme", getDepartment(2)),
                        new Province("Huaylas", getDepartment(2)),
                        new Province("Mariscal Luzuriaga", getDepartment(2)),
                        new Province("Ocros", getDepartment(2)),
                        new Province("Pallasca", getDepartment(2)),
                        new Province("Pomabamba", getDepartment(2)),
                        new Province("Recuy", getDepartment(2)),
                        new Province("Santa", getDepartment(2)),
                        new Province("Sihuas", getDepartment(2)),
                        new Province("Yungay", getDepartment(2)),
                        new Province("ABANCAY", getDepartment(3)),
                        new Province("ANDAHUAYLAS", getDepartment(3)),
                        new Province("ANTABAMBA", getDepartment(3)),
                        new Province("AYMARAES", getDepartment(3)),
                        new Province("COTABAMBAS", getDepartment(3)),
                        new Province("CHINCHEROS", getDepartment(3)),
                        new Province("GRAU", getDepartment(3)),
                        new Province("AREQUIPA", getDepartment(4)),
                        new Province("CAMANA", getDepartment(4)),
                        new Province("CARAVELI", getDepartment(4)),
                        new Province("CASTILLA", getDepartment(4)),
                        new Province("CAYLLOMA", getDepartment(4)),
                        new Province("CONDESUYOS", getDepartment(4)),
                        new Province("ISLAY", getDepartment(4)),
                        new Province("LA UNION", getDepartment(4)),
                        new Province("HUAMANGA", getDepartment(5)),
                        new Province("CANGALLO", getDepartment(5)),
                        new Province("HUANCA SANCOS", getDepartment(5)),
                        new Province("HUANTA", getDepartment(5)),
                        new Province("LA MAR", getDepartment(5)),
                        new Province("LUCANAS", getDepartment(5)),
                        new Province("PARINACOCHAS", getDepartment(5)),
                        new Province("PAUCAR DEL SARA SARA", getDepartment(5)),
                        new Province("SUCRE", getDepartment(5)),
                        new Province("VICTOR FAJARDO", getDepartment(5)),
                        new Province("VILCAS HUAMAN", getDepartment(5)),
                        new Province("CAJAMARCA", getDepartment(6)),
                        new Province("CAJABAMBA", getDepartment(6)),
                        new Province("CELENDIN", getDepartment(6)),
                        new Province("CHOTA", getDepartment(6)),
                        new Province("CONTUMAZA", getDepartment(6)),
                        new Province("CUTERVO", getDepartment(6)),
                        new Province("HUALGAYOC", getDepartment(6)),
                        new Province("JAEN", getDepartment(6)),
                        new Province("SAN IGNACIO", getDepartment(6)),
                        new Province("SAN MARCOS", getDepartment(6)),
                        new Province("SAN PABLO", getDepartment(6)),
                        new Province("SANTA CRUZ", getDepartment(6)),
                        new Province("CALLAO", getDepartment(7)),
                        new Province("CUSCO", getDepartment(8)),
                        new Province("ACOMAYO", getDepartment(8)),
                        new Province("ANTA", getDepartment(8)),
                        new Province("CALCA", getDepartment(8)),
                        new Province("CANAS", getDepartment(8)),
                        new Province("CANCHIS", getDepartment(8)),
                        new Province("CHUMBIVILCAS", getDepartment(8)),
                        new Province("ESPINAR", getDepartment(8)),
                        new Province("LA CONVENCION", getDepartment(8)),
                        new Province("PARURO", getDepartment(8)),
                        new Province("PAUCARTAMBO", getDepartment(8)),
                        new Province("QUISPICANCHI", getDepartment(8)),
                        new Province("URUBAMBA", getDepartment(8)),
                        new Province("HUANCAVELICA", getDepartment(9)),
                        new Province("ACOBAMBA", getDepartment(9)),
                        new Province("ANGARAES", getDepartment(9)),
                        new Province("CASTROVIRREYNA", getDepartment(9)),
                        new Province("CHURCAMPA", getDepartment(9)),
                        new Province("HUAYTARA", getDepartment(9)),
                        new Province("TAYACAJA", getDepartment(9)),
                        new Province("HUANUCO", getDepartment(10)),
                        new Province("AMBO", getDepartment(10)),
                        new Province("DOS DE MAYO", getDepartment(10)),
                        new Province("HUACAYBAMBA", getDepartment(10)),
                        new Province("HUAMALIES", getDepartment(10)),
                        new Province("LEONCIO PRADO", getDepartment(10)),
                        new Province("MARANON", getDepartment(10)),
                        new Province("PACHITEA", getDepartment(10)),
                        new Province("PUERTO INCA", getDepartment(10)),
                        new Province("LAURICOCHA", getDepartment(10)),
                        new Province("YAROWILCA", getDepartment(10)),
                        new Province("ICA", getDepartment(11)),
                        new Province("CHINCHA", getDepartment(11)),
                        new Province("NAZCA", getDepartment(11)),
                        new Province("PALPA", getDepartment(11)),
                        new Province("PISCO", getDepartment(11)),
                        new Province("HUANCAYO", getDepartment(12)),
                        new Province("CONCEPCION", getDepartment(12)),
                        new Province("CHANCHAMAYO", getDepartment(12)),
                        new Province("JAUJA", getDepartment(12)),
                        new Province("JUNIN", getDepartment(12)),
                        new Province("SATIPO", getDepartment(12)),
                        new Province("TARMA", getDepartment(12)),
                        new Province("YAULI", getDepartment(12)),
                        new Province("CHUPACA", getDepartment(12)),
                        new Province("TRUJILLO", getDepartment(13)),
                        new Province("ASCOPE", getDepartment(13)),
                        new Province("BOLIVAR", getDepartment(13)),
                        new Province("CHEPEN", getDepartment(13)),
                        new Province("JULCAN", getDepartment(13)),
                        new Province("OTUZCO", getDepartment(13)),
                        new Province("PACASMAYO", getDepartment(13)),
                        new Province("PATAZ", getDepartment(13)),
                        new Province("SANCHEZ CARRION", getDepartment(13)),
                        new Province("SANTIAGO DE CHUCO", getDepartment(13)),
                        new Province("GRAN CHIMU", getDepartment(13)),
                        new Province("VIRU", getDepartment(13)),
                        new Province("CHICLAYO", getDepartment(14)),
                        new Province("FERNANDEZ", getDepartment(14)),
                        new Province("LAMBAYEQUE", getDepartment(14)),
                        new Province("LIMA", getDepartment(15)),
                        new Province("BARRANCA", getDepartment(15)),
                        new Province("CAJATAMBO", getDepartment(15)),
                        new Province("CANTA", getDepartment(15)),
                        new Province("CAÑETE", getDepartment(15)),
                        new Province("HUARAL", getDepartment(15)),
                        new Province("HUAROCHIRI", getDepartment(15)),
                        new Province("HUAURA", getDepartment(15)),
                        new Province("OYON", getDepartment(15)),
                        new Province("YAUYOS", getDepartment(15)),
                        new Province("MAYNAS", getDepartment(16)),
                        new Province("ALTO AMAZONAS", getDepartment(16)),
                        new Province("LORETO", getDepartment(16)),
                        new Province("MARISCAL RAMON CASTILLA", getDepartment(16)),
                        new Province("REQUENA", getDepartment(16)),
                        new Province("UCAYALI", getDepartment(16)),
                        new Province("TAMBOPATA", getDepartment(17)),
                        new Province("MANU", getDepartment(17)),
                        new Province("TAHUAMANU", getDepartment(17)),
                        new Province("MARISCAL NIETO", getDepartment(18)),
                        new Province("GENERAL SANCHEZ CERRO", getDepartment(18)),
                        new Province("ILO", getDepartment(18)),
                        new Province("PASCO", getDepartment(19)),
                        new Province("DANIEL ALCIDES CARRION", getDepartment(19)),
                        new Province("OXAPAMPA", getDepartment(19)),
                        new Province("PIURA", getDepartment(20)),
                        new Province("AYABACA", getDepartment(20)),
                        new Province("HUANCABAMBA", getDepartment(20)),
                        new Province("MORROPON", getDepartment(20)),
                        new Province("PAITA", getDepartment(20)),
                        new Province("SULLANA", getDepartment(20)),
                        new Province("TALARA", getDepartment(20)),
                        new Province("SECHURA", getDepartment(20)),
                        new Province("PUNO", getDepartment(21)),
                        new Province("AZANGARO", getDepartment(21)),
                        new Province("CARABAYA", getDepartment(21)),
                        new Province("CHUCUITO", getDepartment(21)),
                        new Province("EL COLLAO", getDepartment(21)),
                        new Province("HUANCANE", getDepartment(21)),
                        new Province("LAMPA", getDepartment(21)),
                        new Province("MELGAR", getDepartment(21)),
                        new Province("MOHO", getDepartment(21)),
                        new Province("SAN ANTONIO DE PUTINA", getDepartment(21)),
                        new Province("SAN ROMAN", getDepartment(21)),
                        new Province("SANDIA", getDepartment(21)),
                        new Province("YUNGUYO", getDepartment(21)),
                        new Province("MOYOBAMBA", getDepartment(22)),
                        new Province("BELLAVISTA", getDepartment(22)),
                        new Province("EL DORADO", getDepartment(22)),
                        new Province("HUALLAGA", getDepartment(22)),
                        new Province("LAMAS", getDepartment(22)),
                        new Province("MARISCAL CACERES", getDepartment(22)),
                        new Province("PICOTA", getDepartment(22)),
                        new Province("RIOJA", getDepartment(22)),
                        new Province("SAN MARTIN", getDepartment(22)),
                        new Province("TOCACHE", getDepartment(22)),
                        new Province("TACNA", getDepartment(23)),
                        new Province("CANDARAVE", getDepartment(23)),
                        new Province("JORGE BASADRE", getDepartment(23)),
                        new Province("TARATA", getDepartment(23)),
                        new Province("TUMBES", getDepartment(24)),
                        new Province("CONTRALMIRANTE VILLAR", getDepartment(24)),
                        new Province("ZARUMILLA", getDepartment(24)),
                        new Province("CORONEL PORTILLO", getDepartment(25)),
                        new Province("ATALAYA", getDepartment(25)),
                        new Province("PADRE ABAD", getDepartment(25)),
                        new Province("PURUS", getDepartment(25))
                );

                provinceRepository.saveAll(provinces);
            }
        };
    }
    private Department getDepartment(int id) {
        return departmentRepository.findById(id).orElseThrow(() -> new RuntimeException("Department not found: " + id));
    }
}
